// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1UrKbAt2FUEWGCLF-nEy36wdHNl7vuA',
    appId: '1:370628128960:web:46c5f5c55f64a3fd747d25',
    messagingSenderId: '370628128960',
    projectId: 'gustavoposflutter',
    authDomain: 'gustavoposflutter.firebaseapp.com',
    databaseURL: 'https://gustavoposflutter-default-rtdb.firebaseio.com',
    storageBucket: 'gustavoposflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJAQtIFePzlU6iv67NYepEinDQWzhZCk',
    appId: '1:370628128960:android:0da6ec5a755a6ca6747d25',
    messagingSenderId: '370628128960',
    projectId: 'gustavoposflutter',
    databaseURL: 'https://gustavoposflutter-default-rtdb.firebaseio.com',
    storageBucket: 'gustavoposflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhpf_JfMMx3nFPt7LPPGKffm-Jx7GbaPU',
    appId: '1:370628128960:ios:cd69e2dd28bc48ba747d25',
    messagingSenderId: '370628128960',
    projectId: 'gustavoposflutter',
    databaseURL: 'https://gustavoposflutter-default-rtdb.firebaseio.com',
    storageBucket: 'gustavoposflutter.appspot.com',
    iosBundleId: 'com.example.consultorDePrecos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhpf_JfMMx3nFPt7LPPGKffm-Jx7GbaPU',
    appId: '1:370628128960:ios:8ed68423a5b3f52c747d25',
    messagingSenderId: '370628128960',
    projectId: 'gustavoposflutter',
    databaseURL: 'https://gustavoposflutter-default-rtdb.firebaseio.com',
    storageBucket: 'gustavoposflutter.appspot.com',
    iosBundleId: 'com.example.consultorDePrecos.RunnerTests',
  );
}
